name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        run: |
          cd Platform
          echo $GITHUB_RUN_NUMBER > version.txt
          zip -r plat-vale.zip ./
          gh release create v$GITHUB_RUN_NUMBER 'plat-vale.zip'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
