name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ["ghcr.io/cirruslabs/ubuntu-runner-amd64:22.04-sm"]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        run: |
          echo $GITHUB_RUN_NUMBER > version.txt
          zip -r plat-vale.zip plat-vale
          gh release create v$GITHUB_RUN_NUMBER 'plat-vale.zip' --latest
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
